---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: momo
  labels:
    app: frontend
spec:
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gitlab.praktikum-services.ru:5050/std-015-39/momo-store/momo-frontend:1.0.956016
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
            - key: nginx.conf
              path: default.conf
      imagePullSecrets:
        - name: docker-config-secret
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #         nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: app
      #             operator: In
      #             values:
      #             - frontend
