---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: momo
  annotations:
    kubernetes.io/ingress.class: "nginx"      
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - "momo-store.white-fluff.com"
    secretName: letsencrypt
  rules:
  - host: "momo-store.white-fluff.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: "/auth/whoami"
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: "/products"
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: "/categories"
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
