---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: momo
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }} 
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
