version: "3.7"

services:
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-015-39/momo-store/momo-frontend:${FRONTEND_VERSION}
    pull_policy: always
    restart: unless-stopped
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - momo-store
  backend:
    image: gitlab.praktikum-services.ru:5050/std-015-39/momo-store/momo-backend:${BACKEND_VERSION}
    pull_policy: always
    container_name: backend
    restart: unless-stopped
    expose: 
      - "8081"
    networks:
      - momo-store
    healthcheck:
      test: curl --fail -s http://localhost:8081/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6

networks:
  momo-store:
