workflow:
  rules:
    - if: $CI_COMMIT_TITLE == "start build"

stages:
  - module-pipelines

frontend:
  stage: module-pipelines
  trigger:
    include:
      - local: frontend/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - local: backend/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - backend/**/*
