workflow:
  rules:
    - if: $CI_COMMIT_TITLE == "make it beautiful"

variables:
  # Write down the version from the file here: ./momo-helm-chart/Chart.yaml
   VERSION: 1.0.0

stages:
  - helm-release
  - deploy

release-helm-chart:
  stage: helm-release
  image: alpine/helm:latest
  script:
    - echo "Start Helm Release"
    - helm package ./momo-helm-chart --version ${VERSION}
    - curl -u ${NEXUS_USER}:${NEXUS_PASS} ${NEXUS_REPO_HELM} --upload-file momo-store-helm-chart-${VERSION}.tgz
    - echo "End Helm Release"

deploy:
  stage: deploy
  when: manual
  image: alpine/helm:latest
  environment:
    name: momo-helm-chart
  before_script:
    - echo "Start Depoly"
    - mkdir -p ~/.kube
    - echo ${kubeconfig} | base64 -d > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
  script:
    - helm repo add momo-helm-repo ${NEXUS_REPO_HELM} --username ${NEXUS_USER} --password ${NEXUS_PASS}
    - helm repo update
    - helm upgrade momo-helm-chart momo-helm-repo/momo-helm-chart -i --set image.tag=$VERSION --atomic
    - echo "End Deploy"
