variables:
   VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - test
  - build
  - release
  - notify

include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

go-backend-tests:
  stage: test
  image: golang:alpine3.18
  script:
    - cd backend
    - go test -v ./...

sonarqube-backend-sast:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]  
  script:
    - cd backend
    - |
      sonar-scanner \
        -Dsonar.projectName=momo-store-backend-std-15-39 \
        -Dsonar.projectKey=momo-store-backend-std-15-39 \
        -Dsonar.sources=. \
        -Dsonar.host.url=${SONAR_URL} \
        -Dsonar.login=${SONAR_LOGIN_BACKEND}

build-backend-binary:
  stage: build
  image: golang:1.18-alpine
  needs:
    - sonarqube-backend-sast
    - go-backend-tests
  before_script:
    - apk add curl tar
    - echo "Strating build"
  script:
    - cd backend/cmd/api
    - go build -o momo-strore-back-${VERSION}
    - tar czvf momo-strore-back-${VERSION}.tar.gz momo-strore-back-${VERSION}
    - |
      curl -v -u "${NEXUS_USER}:${NEXUS_PASS}" \
      --upload-file momo-strore-back-${VERSION}.tar.gz ${NEXUS_REPO_BACK}/${VERSION}/momo-strore-back-${VERSION}.tar.gz

build-backend-container:
  stage: build
  image: docker:24.0.7-dind-rootless
  needs:
    - sonarqube-backend-sast
    - go-backend-tests
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD gitlab.praktikum-services.ru:5050
    - docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASS
  script:
    - cd backend
    - |
      docker build \
      --build-arg VERSION=$VERSION \
      --tag $CI_REGISTRY_IMAGE/momo-backend:$VERSION \
      .
    - docker push $CI_REGISTRY_IMAGE/momo-backend:$VERSION

update-latest-image:
  stage: release
  when: manual
  image: docker:24.0.7-dind-rootless
  needs:
    - build-backend-container
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD gitlab.praktikum-services.ru:5050
  script:
    - docker pull $CI_REGISTRY_IMAGE/momo-backend:$VERSION
    - docker tag $CI_REGISTRY_IMAGE/momo-backend:$VERSION $CI_REGISTRY_IMAGE/momo-backend:latest
    - docker push $CI_REGISTRY_IMAGE/momo-backend:latest

telegram-release-notification:
  stage: notify
  image: python:3.12-slim
  needs:
    - update-latest-image
  before_script:
    - pip install requests
    - python notify.py --help
  script:
    - python notify.py --service=BACKEND --artifact=$NEXUS_REPO --version=$VERSION
