---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: momo
  labels:
    app: backend
spec:
  revisionHistoryLimit: 15
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 80%
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-015-39/momo-store/momo-backend:1.0.956017
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret