---
apiVersion: v2
type: application
name: momo-store
description: Momo Store Helm Chart

version: 1.0.0
appVersion: "latest"

dependencies:
  - name: backend
    version: 1.0.0
  - name: frontend
    version: 1.0.0